bomberoschile/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from bomberoschile.views import login_view, logout_view
from main.views import *

urlpatterns = [
                  path('grappelli/', include('grappelli.urls')), # grappelli URLS
                  path('admin/', admin.site.urls),
                  path('chaining/', include('smart_selects.urls')),
                  path('index/', bitacora_list, name='bitacora_list'),
                  path('', bitacora_list, name='bitacora_list'),
                  # path(r'^index/$', index_view,name='index_view'),
                  path('login/', login_view, name='login_view'),
                  path('logout/', logout_view, name='logout_view'),
                  # BITACORA
                  path('bitacora/add/', bitacora_create_view, name='bitacora_create_view'),
                  path('bitacora/', bitacora_list, name='bitacora_list'),
                  path('bitacora/detalle/<str:pk>/', bitacora_detail, name='bitacora_detail'),
                  path('bitacora/editar/<str:pk>/', bitacora_update, name='bitacora_update'),
                  path('bitacora/eliminar/<str:pk>/', bitacora_delete, name='bitacora_delete'),
                  # MANTENCIONES
                  # path(r'^mantencion/add/$', mantencion_create, name='mantencion_create'),
                  path('mantencion/add/', mantencion_create_view, name='mantencion_create_view'),
                  path('mantencion/add/nuevo', mantencion_form_view, name='mantencion_form_view'),
                  path('mantencion/add/detalle', detalle_mantencion_form_view, name='detalle_mantencion_form_view'),
                  path('mantencion/add/repuesto', repuesto_detalle_mantencion_form_view,
                       name='repuesto_detalle_mantencion_form_view'),
                  # path(r'^mantencion/add_detalle/$', mantencion_add_detalle, name='mantencion_add_detalle'),
                  # path(r'^mantencion/add_repuesto/$', mantencion_add_repuesto, name='mantencion_add_repuesto'),
                  path('mantenciones/', mantencion_list, name='mantencion_list'),
                  path('mantencion/detalle/<str:pk>/', mantencion_detail, name='mantencion_detail'),
                  path('mantencion/eliminar/<str:pk>/', mantencion_delete, name='mantencion_delete'),
                  path('mantencion/editar/<str:pk>/', mantencion_update, name='mantencion_update'),
                  # MAQUINA
                  path('maquina/detalle/<str:pk>/', maquina_detail, name='maquina_detail'),
                  path('maquinas/', maquina_list, name='maquina_list'),
                  path('maquina/add/', maquina_create, name='maquina_create'),
                  path('maquina/editar/<str:pk>/', maquina_update, name='maquina_update'),
                  path('maquina/eliminar/<str:pk>/', maquina_delete, name='maquina_delete'),
                  path('get_maquina_conductores/', get_maquina_conductores, name='get_maquina_conductores'),
                  path('get_parametros_maquina/', get_parametros_maquina, name='get_parametros_maquina'),

                  # CONDUCTORES
                  path('conductores/', conductor_list, name='conductor_list'),
                  path('conductor/detalle/<str:pk>/', conductor_detail, name='conductor_detail'),
                  path('conductor/add/', conductor_create, name='conductor_create'),
                  path('conductor/editar/<str:pk>/', conductor_update, name='conductor_update'),
                  path('conductor/eliminar/<str:pk>/', conductor_delete, name='conductor_delete'),

                  # COMBUSTIBLE
                  path('combustible/add/', combustible_create, name='combustible_create'),
                  path('carga-combustible/', combustible_list, name='combustible_list'),
                  path('carga-combustible/eliminar/<str:pk>/', combustible_delete, name='combustible_delete'),
                  path('carga-combustible/detalle/<str:pk>/', combustible_detail, name='combustible_detail'),
                  path('carga-combustible/editar/<str:pk>/', combustible_update, name='combustible_update'),

                  # DASHBOARD
                  path('dashboard/', dashboard_list_view, name='dashboard_list_view'),

                  # REPORTES
                  path('reporte/parte-combustible/', reporte_combustible_list_view,
                       name='reporte_combustible_list_view'),
                  path('reporte/maquinistas/', reporte_maquinistas_list_view, name='reporte_maquinistas_list_view'),
                  path('reporte/servicios/', reporte_servicios_list_view, name='reporte_servicios_list_view'),
                  path('reporte/mantenciones/', reporte_mantenciones_list_view, name='reporte_mantenciones_list_view'),
                  path('reporte/talleres/', reporte_talleres_list_view, name='reporte_talleres_list_view'),
                  path('get_maquinas_company/', get_maquinas_company, name='get_maquinas_company'),

                  # UTIL
                  path('get_all_conductores/', get_all_conductores, name='get_all_conductores'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from smart_selects.db_fields import ChainedForeignKey, GroupedForeignKey, ChainedManyToManyField
from django.contrib.auth.models import User
from django.urls import reverse
import datetime
from django.contrib import messages


class Company(models.Model):
    numero = models.IntegerField()
    nombre = models.CharField(max_length=45)
    direccion = models.CharField(max_length=45)

    class Meta:
        verbose_name = 'Compañía'
        verbose_name_plural = 'Compañías'

    def __str__(self):
        return str(self.nombre)


class Clasificacion_maquina(models.Model):
    nombre = models.CharField(max_length=45)
    descripcion = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = 'Clasificación máquina'

    def __str__(self):
        return str(self.nombre)


class Conductor(models.Model):
    company = models.ForeignKey(Company, null=True, on_delete=models.CASCADE)
    rut = models.CharField(max_length=12, null=True, blank=True)
    nombre = models.CharField(max_length=45, null=True)
    ap_paterno = models.CharField(max_length=45, null=True)
    ap_materno = models.CharField(max_length=45, null=True)
    num_licencia = models.CharField(max_length=12, null=True, blank=True)
    venc_lic = models.DateField(null=True, blank=True)
    observaciones_cond = models.TextField(max_length=1000, null=True, blank=True, default="Ninguna")
    foto = models.FileField(upload_to='profile', null=True, blank=True)

    class Meta:
        verbose_name = 'Conductor'
        verbose_name_plural = 'Conductores'

    def __str__(self):
        nombre = self.nombre
        nombre = nombre.split(" ")
        return nombre[0] + " " + str(self.ap_paterno) + " " + str(self.ap_materno)

    def get_absolute_url(self):
        return reverse('conductor_detail', args=[str(self.id)])


year_dropdown = []
for y in range(1950, (datetime.datetime.now().year + 1)):
    year_dropdown.append((str(y), str(y)))

TIPO_MAQUINA_CHOICES = (
    ('1', 'AMERICANO'),
    ('2', 'EUROPEO'),
)


class Maquina(models.Model):
    nombre = models.CharField(max_length=45)
    clasificacion = models.ForeignKey(Clasificacion_maquina, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    marca = models.CharField(max_length=45, null=True, blank=True)
    modelo = models.CharField(max_length=45, null=True, blank=True)
    ano = models.CharField(max_length=5, choices=year_dropdown, default=datetime.datetime.now().year, null=True,
                           blank=True)
    numero_motor = models.CharField(max_length=45, null=True, blank=True)
    numero_chasis = models.CharField(max_length=45, null=True, blank=True)
    bin = models.CharField(max_length=45, null=True, blank=True)
    patente = models.CharField(max_length=10, null=True, blank=True)
    conductor = models.ManyToManyField(Conductor, blank=True)
    kilometraje = models.DecimalField(decimal_places=1, max_digits=10, null=True, blank=True)
    hodometro = models.DecimalField(decimal_places=1, max_digits=10, null=True, blank=True)
    tiene_bomba = models.BooleanField(default=False, choices=((True, "Si"), (False, "No")))
    hodometro_bomba = models.DecimalField(decimal_places=1, max_digits=10, null=True, blank=True)
    venc_patente = models.DateField(null=True, blank=True)  # vencimiento patente
    costo_patente = models.IntegerField(null=True, blank=True)  # costo patente
    soap_costo = models.IntegerField(null=True, blank=True)  # seguro obligatorio
    venc_rev_tec = models.DateField(null=True, blank=True)  # vencimiento revicion tecnica
    costo_rev_tec = models.IntegerField(null=True, blank=True)  # costo revision tecnica
    costo_seg_auto = models.IntegerField(null=True, blank=True)  # costo seguro automotriz
    venc_seg_auto = models.DateField(null=True, blank=True)
    prueba = models.DecimalField(decimal_places=1, max_digits=10, null=True, blank=True)
    procedencia_maquina = models.CharField(max_length=1, choices=TIPO_MAQUINA_CHOICES, default=1)

    class Meta:
        verbose_name = 'Maquina'
        verbose_name_plural = 'Maquinas'

    def __str__(self):
        return str(self.nombre)

    def get_absolute_url(self):
        return reverse('maquina_detail', args=[str(self.id)])


# class Detalle_Maquina(models.Model):
#     maquina = models.ForeignKey(Maquina)
#     venc_patente = models.DateField()       #vencimiento patente
#     costo_patente = models.IntegerField()   #costo patente
#     soap_costo = models.IntegerField()      #seguro obligatorio
#     venc_rev_tec = models.DateField()       #vencimiento revicion tecnica
#     costo_rev_tec = models.IntegerField()   #costo revision tecnica
#     costo_seg_auto = models.IntegerField()  #costo seguro automotriz
#     venc_seg_auto = models.DateField(null=True)


TIPO_USER_CHOICES = (
    ('0', 'Teniente de máquina'),
    ('1', 'OBAC'),
    ('2', 'Inspector general de máquina'),
    ('3', 'Comandante')
)


class UsuarioComp(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=1, choices=TIPO_USER_CHOICES)
    company = models.ForeignKey(Company, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Usuario Compañía'

    def __str__(self):
        return str(self.user)

    def get_tipo(self):
        return self.tipo


class Servicentro(models.Model):
    nombre = models.CharField(max_length=45)
    direccion = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Servicentro'
        verbose_name_plural = 'Servicentros'

    def __str__(self):
        return self.nombre + " - " + self.direccion


class Taller(models.Model):
    tipo = models.CharField(max_length=45)
    razon_social = models.CharField(max_length=45)
    rut = models.CharField(max_length=12, null=True, blank=True)
    telefono = models.IntegerField(null=True, blank=True)
    contacto = models.CharField(max_length=45, null=True, blank=True)
    tel_contacto = models.IntegerField(null=True, blank=True)
    direccion = models.CharField(max_length=60, null=True, blank=True)
    correo = models.EmailField(max_length=45, null=True, blank=True)

    class Meta:
        verbose_name = 'Taller'
        verbose_name_plural = 'Talleres'

    def __str__(self):
        return str(self.razon_social)


class Componente(models.Model):
    nombre = models.CharField(max_length=45)
    descripcion = models.TextField(max_length=100)

    class Meta:
        verbose_name = 'Componente'
        verbose_name_plural = 'Componentes'

    def __str__(self):
        return str(self.nombre)


class Division(models.Model):
    nombre = models.CharField(max_length=45)

    class Meta:
        verbose_name = 'División'
        verbose_name_plural = 'Divisiones'

    def __str__(self):
        return str(self.nombre)


class TipoMantencion(models.Model):
    nombre = models.CharField(max_length=45)
    descripcion = models.TextField(max_length=100)

    class Meta:
        verbose_name = 'Tipo Mantención'

    def __str__(self):
        return str(self.nombre)


class Subdivision(models.Model):
    division = models.ForeignKey(Division, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=45)

    class Meta:
        verbose_name = 'Subdivisión'
        verbose_name_plural = 'Subdivisiones'

    def __str__(self):
        return str(self.nombre)


class ServicioMantencion(models.Model):
    division = models.ForeignKey(Division, null=True, on_delete=models.CASCADE)
    subdivision = ChainedForeignKey(Subdivision, chained_field="division", chained_model_field="division",
                                    related_name='%(class)s_requests_created', null=True, on_delete=models.CASCADE)
    # tipo_mantencion = models.ForeignKey(TipoMantencion)
    nombre = models.CharField(max_length=45)
    descripcion = models.CharField(max_length=75, null=True, blank=True)

    class Meta:
        verbose_name = 'Servicio Mantención'

    def __str__(self):
        return str(self.nombre)


class Clave(models.Model):
    nombre = models.CharField(max_length=45)
    descripcion = models.CharField(max_length=100)
    habilitado = models.BooleanField(default=True, choices=((True, "Si"), (False, "No")))

    class Meta:
        verbose_name = 'Clave'
        verbose_name_plural = 'Claves'

    def __str__(self):
        return str(self.nombre) + ' - ' + str(self.descripcion)


class Bitacora(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    maquina = ChainedForeignKey(Maquina, chained_field="company", chained_model_field="company",
                                related_name='%(class)s_requests_created', on_delete=models.CASCADE)
    conductor = ChainedForeignKey(Conductor, chained_field="maquina", chained_model_field="maquina", null=True, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=100, null=True)
    fecha = models.DateField(auto_now=False, auto_now_add=False, null=True)
    hora_salida = models.TimeField(null=True)
    hora_llegada = models.TimeField(null=True)
    clave = models.ForeignKey(Clave, null=True, on_delete=models.CASCADE)
    kilometraje_salida = models.DecimalField(decimal_places=1, max_digits=10, null=True)
    kilometraje_llegada = models.DecimalField(decimal_places=1, max_digits=10, null=True)
    hodometro_salida = models.DecimalField(decimal_places=1, max_digits=10, null=True)
    hodometro_llegada = models.DecimalField(decimal_places=1, max_digits=10, null=True)
    ho_bomba_salida = models.DecimalField(decimal_places=1, max_digits=10, null=True, blank=True)
    ho_bomba_regreso = models.DecimalField(decimal_places=1, max_digits=10, null=True, blank=True)
    observciones = models.TextField(max_length=300, null=True)

    class Meta:
        verbose_name = 'Bitacora'

    def __str__(self):
        return str(self.id) + ' - ' + str(self.company) + ' - ' + str(self.maquina) + ' - ' + str(

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/bomberos-mini.png' %}"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8">

    <title>Cuerpo Bomberos Osorno</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}">
    <!-- bootstrap-progressbar -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}">
    <!-- bootstrap-wysiwyg -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/google-code-prettify/bin/prettify.min.css' %}">
    <!-- Select2 -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/select2/dist/css/select2.min.css' %}">


    <!-- Custom Theme Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'js/datepicker/datepicker.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/datetime-picker/bootstrap-datetimepicker.min.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.2.0/jquery-confirm.min.css">



    <!--<script type="text/javascript" src="/static/admin/js/jquery.js"></script>-->
    <!--<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>-->

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{% url 'dashboard_list_view' %}" class="site_title"><span>MATERIAL MAYOR</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile">
              <div class="profile_pic">
                <img src="{% static 'images/logo_comandancia_mini.png' %}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <h2>Bienvenido Usuario:
                {% if user.is_authenticated %}

                {% endif %}
                </h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
              {% if user.is_authenticated %}
                  <h3>{{ user.username }}</h3>
                  <h3>{{ user.usuariocomp.get_tipo_display }}</h3>
                {% endif %}
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'dashboard_list_view' %}">Dashboard</a>
                      </li>
                    </ul>
                  </li>
                  {% if perms.main.add_bitacora %}
                    <li><a><i class="fa fa-table"></i> Bitacora<span class="fa fa-chevron-down"></span></a>
                      <ul class="nav child_menu">
                        <li><a href="{% url 'bitacora_list' %}">Lista de Servicios</a>
                        </li>
                        <li><a href="{% url 'bitacora_create_view' %}">Nuevo servicio</a>
                        </li>
                        <li><a href="{% url 'combustible_list' %}">Cargas Combustible</a>
                        </li>
                        <li><a href="{% url 'mantencion_create_view' %}">Nueva Mantención</a>
                        </li>
                        <li><a href="{% url 'mantencion_list' %}">Lista Mantenciones</a>
                        </li>
                      </ul>
                    </li>
                  {% endif %}
                  {% if user.usuariocomp.tipo == "2" or user.usuariocomp.tipo == "3" %}
                    <li><a><i class="fa fa-cogs"></i> Mantenimiento <span class="fa fa-chevron-down"></span></a>
                      <ul class="nav child_menu">
                        {% if perms.main.add_division %}
                        <li><a href="{% url 'admin:main_division_add' %}">Agregar y Editar Divisiones</a>
                        </li>
                        {% endif %}
                        {% if perms.main.add_subdivision %}
                        <li><a href="{% url 'admin:main_subdivision_add' %}">Agregar y Editar SubDivisiones</a>
                        </li>
                        {% endif %}
                        {% if perms.main.add_serviciomantencion %}
                        <li><a href="{% url 'admin:main_serviciomantencion_add' %}">Agregar y Editar Servicios</a>
                        </li>
                        {% endif %}
                        {% if perms.main.add_taller %}
                        <li><a href="{% url 'admin:main_taller_add' %}">Agregar y Editar Talleres</a>
                        </li>
                        {% endif %}
                        {% if perms.main.add_servicentro %}
                        <li><a href="{% url 'admin:main_servicentro_add' %}">Agregar y Editar Servicentros</a>
                        </li>
                        {% endif %}
                      </ul>
                    </li>
                  {% endif %}
                  {% if user.usuariocomp.tipo != "1" %}
                    <li><a><i class="fa fa-edit"></i> Personal y Máquinas <span class="fa fa-chevron-down"></span></a>
                      <ul class="nav child_menu">
                        <li><a href="{% url 'maquina_list' %}">Máquinas</a>
                        </li>
                        {% if perms.main.add_clasificacion_maquina %}
                        <li><a href="{% url 'admin:main_clasificacion_maquina_add' %}">Agregar tipos de máquinas</a>
                        </li>
                        {% endif %}
                        <li><a href="{% url 'conductor_list' %}">Conductores</a>
                        </li>
                        <!--li><a href="">Form Validation</a>
                        </li>-->
                      </ul>
                    </li>
                  {% endif %}
                  {% if user.usuariocomp.tipo != "1" %}
                    <li><a><i class="fa fa-area-chart"></i> Reportes <span class="fa fa-chevron-down"></span></a>
                      <ul class="nav child_menu">
                        <li><a href="{% url 'reporte_combustible_list_view' %}">Parte de Combustible</a>
                        </li>
                        <li><a href="{% url 'reporte_maquinistas_list_view' %}">Reporte Maquinistas</a>
                        </li>
                        <li><a href="{% url 'reporte_servicios_list_view' %}">Reporte Servicios</a>
                        </li>
                        <li><a href="{% url 'reporte_mantenciones_list_view' %}">Reporte Mantenciones</a>
                        </li>
                        <li><a href="{% url 'reporte_talleres_list_view' %}">Reporte Talleres</a>
                        </li>
                      </ul>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">

          <div class="nav_menu">
            <nav class="" role="navigation">
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="{% static 'images/logo_comandancia_mini.png' %}" alt=""><strong>{% if user.is_authenticated %}
                                                                                <strong>{{ user.username }}</strong>
                                                                              {% endif %}</strong>{{ first_name }}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li>
                      <a href="{% url 'admin:index' %}">Administrador</a>
                    </li>
                    <li><a href="{% url 'logout_view' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->


        <!-- page content -->
        {% block content %}
        {% endblock %}

        <!-- /page content -->

  </body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Bomberos Osorno</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

    <style>          
           body::after {
             content: "";
             background: url("{% static 'images/logo_comandancia_2.png' %}");
             opacity: 0.4;
             top: 0;
             left: 0;
             bottom: 0;
             right: 0;
             position: absolute;
             z-index: -1;
             background-repeat:no-repeat;
           }           
        </style>
  </head>

  <body style="background:#F7F7F7;">
  <!--<body style="background-color:#F7F7F7;
            background-image:url({% static 'images/bomberos-logo.png' %});
            background-repeat: no-repeat;background-attachment: fixed;
            background-position: center; ">
    <div class="">-->
      <a class="hiddenanchor" id="toregister"></a>
      <a class="hiddenanchor" id="tologin"></a>

      <div id="wrapper">
        <div id="login" class=" form">
          <section class="login_content">
            <form method="post">{% csrf_token %}
              <h1>Identificación</h1>
              {{form.as_p}}
              <div>
              <button type="submit" class="btn btn-default submit">Entrar</button>
                {% if message %}
                  <b>{{ message }}</b>
                {% endif %}
              </div>
              <div class="clearfix"></div>
              <div class="separator">
                <div class="clearfix"></div>
                <br />
                <div>
                  <h1>Cuerpo de Bomberos Osorno</h1>
                    <h1> Material Mayor</h1>

                  <p>©Todos los derechos reservados.</p>
                </div>
              </div>
            </form>
          </section>
        </div>
      </div>
    </div>
  </body>
</html>

templates/mantencion_delete.html
{% extends 'base.html' %}

{% block content %}

{% load static %}



        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Eliminar Mantención</h2>

                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                        <form action="" method="post">{% csrf_token %}
                            <p>¿Estas seguro de eliminar la mantencion "{{ object }}" del sistema?</p>
                            <input class="btn btn-danger" type="submit" value="Confirmar" />
                            <button type="button" onclick="location.href='{% url 'mantencion_detail' pk=object.id %}';" class="btn btn-success">Cancelar</button>
                        </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
      </div>
    </div>
    <!-- jQuery -->
    <script type="text/javascript" src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script type="text/javascript" src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- Custom Theme Scripts -->
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

{% endblock %}